# Generated by Django 5.2.13 on 2026-05-07 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0002_seed_tags"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="click",
            new_name="clicks_url_id_f6448b_idx",
            old_name="clicks_url_clicked_at_idx",
        ),
        migrations.RenameIndex(
            model_name="url",
            new_name="urls_created_71be6f_idx",
            old_name="urls_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="url",
            new_name="urls_click_c_24db78_idx",
            old_name="urls_click_count_idx",
        ),
        migrations.RenameIndex(
            model_name="url",
            new_name="urls_is_acti_847f2f_idx",
            old_name="urls_is_active_expires_idx",
        ),
        migrations.RenameIndex(
            model_name="url",
            new_name="urls_owner_i_bf6c03_idx",
            old_name="urls_owner_created_at_idx",
        ),
    ]
