# Generated by Django 5.2.13 on 2026-04-22 09:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("shortener", "0002_seed_default_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Click",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("referrer", models.URLField(blank=True, max_length=2048, null=True)),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "clicks",
            },
        ),
        migrations.AddField(
            model_name="url",
            name="click_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="url",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="url",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="url",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="urls", to="shortener.tag"
            ),
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "tier",
                    models.CharField(
                        choices=[("free", "Free"), ("pro", "Pro"), ("team", "Team")],
                        default="free",
                        max_length=10,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="url",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="urls",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["short_code"], name="urls_short_c_484089_idx"),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["owner"], name="urls_owner_i_e0a75f_idx"),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["created_at"], name="urls_created_71be6f_idx"),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(fields=["click_count"], name="urls_click_c_24db78_idx"),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(
                fields=["is_active", "expires_at"], name="urls_is_acti_847f2f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="url",
            index=models.Index(
                fields=["owner", "created_at"], name="urls_owner_i_bf6c03_idx"
            ),
        ),
        migrations.AddField(
            model_name="click",
            name="url",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clicks",
                to="shortener.url",
            ),
        ),
        migrations.AddIndex(
            model_name="click",
            index=models.Index(fields=["url"], name="clicks_url_id_d3d911_idx"),
        ),
        migrations.AddIndex(
            model_name="click",
            index=models.Index(fields=["clicked_at"], name="clicks_clicked_fa0a3b_idx"),
        ),
        migrations.AddIndex(
            model_name="click",
            index=models.Index(
                fields=["url", "clicked_at"], name="clicks_url_id_f6448b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="click",
            index=models.Index(fields=["country"], name="clicks_country_72af72_idx"),
        ),
    ]
