# Generated by Django 5.2.13 on 2026-04-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shortener",
            "0003_click_url_click_count_url_expires_at_url_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddConstraint(
            model_name="url",
            constraint=models.UniqueConstraint(
                fields=("owner", "original_url"), name="uniq_owner_original_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="url",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner__isnull", True)),
                fields=("original_url",),
                name="uniq_anon_original_url",
            ),
        ),
    ]
