# Generated by Django 5.2.13 on 2026-05-19 10:25

import django.core.validators
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0004_remove_preview_field_uniqueness"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="custom_alias",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Custom alias may only contain letters, numbers, hyphens and underscores",
                        regex="^[A-Za-z0-9_-]+$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="url",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("custom_alias"),
                condition=models.Q(("custom_alias__isnull", False)),
                name="uniq_lower_custom_alias",
            ),
        ),
    ]
